### ISSUE TITLE
Error trying to start demo

### ISSUE THREAD

**Issue by romanoff** [mihaip/react-closure-compiler#12]
Got error trying to run demo.

Ubuntu 15.04

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.15.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

Apache Ant(TM) version 1.9.4 compiled on January 27 2015

I also created manually ../plovr/build/ folder and put plovr.jar 3.1 (as I understand, it doesn't work with 4.0 at this point)

```
andrey@andrey-XPS:~/Programming/react/react-closure-compiler$ ant run-demo 
Buildfile: /home/andrey/Programming/react/react-closure-compiler/build.xml

compile:
    [javac] /home/andrey/Programming/react/react-closure-compiler/build.xml:23: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

jar:

run-demo:
     [java] Listening on /0:0:0:0:0:0:0:0:9810
     [java] Aug 26, 2015 9:06:59 PM org.plovr.Config getCompilerOptions
     [java] INFO: Compiling with level: ADVANCED_OPTIMIZATIONS
     [java] Aug 26, 2015 9:07:02 PM org.plovr.AbstractGetHandler handle
     [java] SEVERE: Error during GET request to /compile?id=demo
     [java] java.lang.NoSuchMethodError: com.google.javascript.rhino.JSDocInfoBuilder.build(Lcom/google/javascript/rhino/Node;)Lcom/google/javascript/rhino/JSDocInfo;
     [java] 	at info.persistent.react.jscomp.ReactCompilerPass.addExterns(ReactCompilerPass.java:147)
     [java] 	at info.persistent.react.jscomp.ReactCompilerPass.process(ReactCompilerPass.java:123)
     [java] 	at com.google.javascript.jscomp.Compiler.process(Compiler.java:877)
     [java] 	at com.google.javascript.jscomp.Compiler.runCustomPasses(Compiler.java:923)
     [java] 	at com.google.javascript.jscomp.Compiler.check(Compiler.java:832)
     [java] 	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:758)
     [java] 	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:94)
     [java] 	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:657)
     [java] 	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:654)
     [java] 	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:701)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] 
```
